### PR TITLE
Add HUE-SHIFT to toolkit

### PR DESCRIPTION
**Pull request by phoe**

### CODE REVIEW

**Comment by Shinmera** [comment]
I don't know that I like adding a dependency and function to `base` that has nothing to do with any of the widgets.

**Comment by Shinmera** [comment]
Having to cons up a list and vector for simple-rgb also seems pretty bad, especially since it happens in the tight loop.

**Comment by phoe** [comment]
Yep, I see your points. What better options do we have to implement that function?

**Comment by phoe** [comment]
I could pull all the guts out of the simple-rgb functions and rewrite them to avoid consing altogether. That will mean that we get a new body of code though, and either we embed it straight into Qtools and deal with the MIT licecnse, or create a Yet Another Common Lisp Color Processing Library™ that we'll need to depend on.

**Comment by Shinmera** [comment]
To be honest I'm not sure this image hue shifting is general enough to fit into qui anyway unless there's an entire collection for image filtering.

Naturally if you keep it in your application, you can write your own shifter no problem, too.

**Comment by phoe** [comment]
What other functions do you mean by a "collection"? I could yak shave some more and write some general Qimage utilities, then put them in some kind of `qtools-ui-qimage-tools` system.

**Comment by Shinmera** [comment]
Well there's plenty of things you can do with colour space conversions. HSV/L/I adaptation, contrast/brightness shift, levelling, etc. Just look at any image manipulation program.

**Comment by Shinmera** [comment]
By the way, there's the qimageblitz smoke module that should be bundled with qtools which offers such functionality. Maybe you'll want to look at that instead of rolling your own.

**Comment by phoe** [comment]
OK. Will you accept a PR in which I create a system for qimage utilities and then gradually fill it up with utils?

I'm slowly getting the Blitz to work.

**Comment by Shinmera** [comment]
Sure!

**Pull request closed without merging**
